### ISSUE TITLE
Propuesta de Solución 

### ISSUE THREAD

**Issue by JuanDanielDimasAmador** [JuanDanielDimasAmador/proyecto_final#12]
# Instrucciones. 
Los integrantes del issue deberán realizar lo siguiente: 

   * Escritura del Objetivo Específico y Objetivos Generales. 
   * Describir de manera general el funcionamiento de la plataforma. 
   * Proponer la tecnologías bajo las cuales debe desarrollarse. 
   * Representar el funcionamiento de la plataforma de manera gráfica / visual. 

Los puntos antes de descritos deberán encontrarse en el siguiente documento colaborativo. [Documento Colaborativo](https://docs.google.com/document/d/1_-7l1ECMWihMoZqOS_PQ49BGssawYkcPBd13S66xWYk/edit).

Al finalizar de la actividad, deberán preparar la presentación para el asesor. 

**FECHA DE ENTREGA**
### VIERNES 29 DE JUNIO DE 2018 A LAS 18:00 PARA REVISIÓN

@OswaldoGarTIC  @lizethortega

**Comment by JuanDanielDimasAmador** [comment]
**FECHA DE ENTREGA**
### VIERNES 29 DE JUNIO DE 2018 A LAS 18:00 PARA REVISIÓN

@OswaldoGarTIC @danCortes0209 @lizethortega

**Comment by OswaldoGarTIC** [comment]
Se ha concluido con exito la tarea asignada, la presentación se encuentra en el siguiente enlace. [Presentación](https://docs.google.com/presentation/d/1m8-4aUPKOLsesPhCOY5rn-O9pyaHkJQr7jdVDfLEnjo/edit#slide=id.g3cb68f28bd_0_478)
