### ISSUE TITLE
Canal de Comunicación Remota

### ISSUE THREAD

**Issue by JuanDanielDimasAmador** [JuanDanielDimasAmador/proyecto_final#7]
Creación de los canales de comunicación para el equipo. 

Aplicación de Videoconferencia: **Discord**
Tareas:
1. Creaciónn del Canal "Proyecto Final"
2. Envíar invitaciones a los miembros del equipo. 
3. Comentar link de invitación al concluir la tarea, para que esté al alcance del equipo. 
4. Proponer reglas de conviviencia. 

@danCortes0209

**Comment by danCortes0209** [comment]
Canal de Discord creado. Canales y reglas asignados. Solamente falta la entrada de todos los usuarios
[https://discord.gg/KfW7hSe](Discord).
